import { useEffect, useRef, useState } from 'react';
import type { EmotionClips } from '../../stores/livePortraitStore';

/**
 * LivePortraitVideo — drop-in replacement for `<Avatar>` that plays a looping
 * MP4 clip generated by the backend's Sieve integration. Cross-fades between
 * an idle clip (when the AI isn't talking) and an emotion clip (when it is).
 *
 * Falls back gracefully: if no idle clip exists in the supplied clip map, the
 * caller should render the static `<Avatar>` instead — this component
 * assumes at least an `idle` entry is present.
 */

export interface LivePortraitVideoProps {
  /** Clip URL map keyed by emotion name (idle, happy, sad, …). */
  clips: EmotionClips;
  /** Current emotion to play on top of idle. `null` plays idle alone. */
  emotion?: string | null;
  /** Diameter of the avatar in CSS pixels (square). Ignored when `fill` is true. */
  size?: number;
  /** "circle" | "square" — matches the existing Avatar shape prop. */
  shape?: 'circle' | 'square';
  /** Optional className on the outer wrapper. */
  className?: string;
  /** Fill the parent container (100% × 100%) instead of using a fixed `size`. */
  fill?: boolean;
}

const FADE_MS = 250;

export function LivePortraitVideo({
  clips,
  emotion = null,
  size = 80,
  shape = 'circle',
  className,
  fill = false,
}: LivePortraitVideoProps) {
  const idleRef = useRef<HTMLVideoElement>(null);
  const emotionRef = useRef<HTMLVideoElement>(null);
  // The active emotion overlay URL — null means "play idle only".
  const [overlayUrl, setOverlayUrl] = useState<string | null>(null);

  // When the requested emotion changes, pick the matching clip URL and fade
  // it in. If no clip exists for that emotion, fall back to no overlay.
  useEffect(() => {
    if (!emotion) {
      setOverlayUrl(null);
      return;
    }
    const url = clips[emotion];
    setOverlayUrl(url ?? null);
  }, [emotion, clips]);

  // Autoplay both videos. Some mobile browsers require an explicit play()
  // call after metadata loads.
  useEffect(() => {
    const v = idleRef.current;
    if (!v) return;
    const tryPlay = () => v.play().catch(() => {});
    v.addEventListener('loadedmetadata', tryPlay);
    tryPlay();
    return () => v.removeEventListener('loadedmetadata', tryPlay);
  }, []);

  useEffect(() => {
    const v = emotionRef.current;
    if (!v) return;
    if (!overlayUrl) return;
    v.play().catch(() => {});
  }, [overlayUrl]);

  const radius = shape === 'circle' ? '50%' : '8px';
  const idleUrl = clips.idle;

  return (
    <div
      className={className}
      style={{
        position: 'relative',
        width: fill ? '100%' : size,
        height: fill ? '100%' : size,
        flexShrink: fill ? undefined : 0,
        overflow: 'hidden',
        borderRadius: radius,
      }}
    >
      {idleUrl && (
        <video
          ref={idleRef}
          src={idleUrl}
          muted
          loop
          playsInline
          autoPlay
          style={{
            position: 'absolute',
            inset: 0,
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            opacity: overlayUrl ? 0 : 1,
            transition: `opacity ${FADE_MS}ms ease`,
          }}
        />
      )}
      {overlayUrl && (
        <video
          ref={emotionRef}
          src={overlayUrl}
          muted
          loop
          playsInline
          autoPlay
          style={{
            position: 'absolute',
            inset: 0,
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            opacity: 1,
            transition: `opacity ${FADE_MS}ms ease`,
          }}
        />
      )}
    </div>
  );
}
