#!/bin/sh
# Runs before SillyTavern on first boot.
# Writes a minimal config.yaml if none exists yet, disabling whitelist mode
# so the nginx reverse proxy can forward requests to the ST API.
# ST will add all missing config values itself on startup.

CONFIG="/home/node/app/config/config.yaml"

if [ ! -f "$CONFIG" ]; then
  echo "[st-init] Writing base config.yaml (whitelist disabled)..."
  cat > "$CONFIG" <<'EOF'
# Auto-generated by st-init.sh on first boot.
# SillyTavern will add remaining defaults on startup.

# Keep whitelistMode: true so ST's startup security check passes.
# Add 'frontend' as a hostname entry — Docker's internal DNS resolves
# it to the nginx container's current IP on every restart, keeping
# all reverse-proxied API calls automatically whitelisted.
whitelistMode: true
enableUserAccounts: true
listen: true
whitelist:
  - 127.0.0.1
  - frontend
EOF
fi

exec node /home/node/app/server.js "$@"
