#!/bin/sh
# Runs before SillyTavern on first boot.
# Writes a minimal config.yaml if none exists yet.
# ST will add all missing config values itself on startup.

CONFIG="/home/node/app/config/config.yaml"

if [ ! -f "$CONFIG" ]; then
  echo "[st-init] Writing base config.yaml..."
  cat > "$CONFIG" <<'EOF'
# Auto-generated by st-init.sh on first boot.
# SillyTavern will add remaining defaults on startup.

# whitelistMode: true satisfies ST's startup security check.
# ST runs in the frontend container's network namespace, so nginx
# connects to localhost:8000 — ST always sees 127.0.0.1, which is
# whitelisted. Port 8000 is never exposed externally.
whitelistMode: true
enableUserAccounts: true
listen: true
whitelist:
  - 127.0.0.1
EOF
fi

exec node /home/node/app/server.js "$@"
