#!/bin/sh
# Runs before SillyTavern on first boot.
# Writes a minimal config.yaml if none exists yet.
# ST will add all missing config values itself on startup.

CONFIG="/home/node/app/config/config.yaml"

if [ ! -f "$CONFIG" ]; then
  echo "[st-init] Writing base config.yaml..."
  cat > "$CONFIG" <<'EOF'
# Auto-generated by st-init.sh on first boot.
# SillyTavern will add remaining defaults on startup.

# whitelistMode: true satisfies ST's startup security check.
# enableForwardedWhitelist: true makes ST use X-Forwarded-For for
# whitelist checks instead of the direct connection IP. nginx always
# sets X-Forwarded-For: 127.0.0.1 so all proxied traffic is allowed.
# Port 8000 is not exposed externally so this cannot be spoofed.
whitelistMode: true
enableForwardedWhitelist: true
enableUserAccounts: true
listen: true
whitelist:
  - 127.0.0.1
EOF
fi

exec node /home/node/app/server.js "$@"
